// <auto-generated />
using Memenim.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Memenim.Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20201206010242_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Memenim.Storage.Entities.PostCommentDraft", b =>
                {
                    b.Property<uint>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "PostId");

                    b.ToTable("PostCommentDrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
